name: radio_web
description: Radio Web
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.17.0 <=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_web_plugins:
    sdk: flutter

    # Dart data class
  json_annotation: ^4.6.0
  equatable: ^2.0.5
    # Network
  dio: ^4.0.0
    # State management
  bloc: ^8.1.0 # ^7.2.1
  flutter_bloc: ^8.1.1 #^7.3.3
    # ServiceLocator
  get_it: ^7.2.0
  blur: ^3.1.0
    # UI
  responsive_framework: ^0.2.0
  smooth_page_indicator: ^1.0.0+2 
    # Open URL
  url_launcher: ^6.1.5
    # Firebase
  cloud_firestore: ^3.4.6
  firebase_auth: ^3.7.0 #^1.0.1 #^0.20.1
  firebase_dynamic_links: ^4.3.6 #^0.8.0=
  firebase_messaging: ^13.0.0 #^9.1.0
  firebase_storage:  ^10.3.7  #^8.0.1 #^7.0.0
  location: ^4.2.0
  geolocator: ^9.0.1
  #assets_audio_player: ^3.0.4+3
  flutter_neumorphic: ^3.2.0
  carousel_slider: ^4.1.1
  #assets_audio_player_web: ^3.0.4+3
  cached_network_image: ^3.2.2
  font_awesome_flutter: ^10.1.0
  transition: ^2.0.2
  flutter_weather_bg_null_safety: ^1.0.0  
  googleapis_auth: ^1.3.1
  syncfusion_flutter_datagrid: ^20.2.48
  video_player_web_hls: ^0.1.11+4 
  video_player: ^2.4.7
  #ext_video_player: ^0.1.2
  #chewie: ^1.3.4

  #pod_player: ^0.1.0
  

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  # Testing
  bloc_test: ^9.1.0
  mockito: ^5.3.0

flutter:

  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: AssetAudioPlayer
      fonts:
        - asset: fonts/AssetAudioPlayer.ttf
    - family: NotoSans
      fonts:
        - asset: fonts/NotoSans-Regular.ttf
